qcacld-3.0: fix compilation with GCC 9
This should be a temporary change untill __popcountdi2
support is added to GCC 9. implementation taken from
https://github.com/HelenOS/helenos/commit/860a7bb68c0de53fb36b554589d46522e847b95e,
fixes:

drivers/built-in.o: In function `wma_get_num_of_setbits_from_bitmask':
esoc-mdm-drv.c:(.text+0x750ea0): undefined reference to `__popcountdi2'
make[1]: *** [/mnt/sda2/MATA_Kernel/Makefile:974: vmlinux] Error 1
make: *** [Makefile:152: sub-make] Error 2

Signed-off-by: Yaroslav Furman <yaro330@gmail.com>